//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace osu_trainer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class ExportBeatmap : global::System.Configuration.ApplicationSettingsBase {
        
        private static ExportBeatmap defaultInstance = ((ExportBeatmap)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ExportBeatmap())));
        
        public static ExportBeatmap Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExportMode {
            get {
                return ((int)(this["ExportMode"]));
            }
            set {
                this["ExportMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExportFolderPath {
            get {
                return ((string)(this["ExportFolderPath"]));
            }
            set {
                this["ExportFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UploadMode {
            get {
                return ((int)(this["UploadMode"]));
            }
            set {
                this["UploadMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int SharexTickInterval {
            get {
                return ((int)(this["SharexTickInterval"]));
            }
            set {
                this["SharexTickInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SharexSkipUploadDetection {
            get {
                return ((bool)(this["SharexSkipUploadDetection"]));
            }
            set {
                this["SharexSkipUploadDetection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SharexBailoutTicks {
            get {
                return ((int)(this["SharexBailoutTicks"]));
            }
            set {
                this["SharexBailoutTicks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SharexPath {
            get {
                return ((string)(this["SharexPath"]));
            }
            set {
                this["SharexPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SharexArguments {
            get {
                return ((string)(this["SharexArguments"]));
            }
            set {
                this["SharexArguments"] = value;
            }
        }
    }
}
